runtime: nodejs20

handlers:
  # Serve all static files with urls ending with a file extension
  - url: /(.*\..+)$
    static_files: dist/client/\1
    upload: dist/client/(.*\..+)$
    secure: always

  # Catch all handler to serve the index page
  - url: /.*
    static_files: dist/client/index.html
    upload: dist/client/index.html
    secure: always

env_variables:
  ADMIN_TOKEN: "jalwa-admin-2023"